# Generated by Django 2.2.5 on 2019-09-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_clase', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('presencial_online', models.SmallIntegerField(blank=True, null=True)),
                ('aula', models.CharField(blank=True, max_length=5, null=True)),
                ('curso', models.ManyToManyField(to='curso.Curso')),
                ('tipo_clase', models.ManyToManyField(to='horario.TipoClase')),
            ],
        ),
    ]
