# Generated by Django 2.2.5 on 2019-09-12 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_evaluacion', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('alumno', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tipo_evaluacion', models.ManyToManyField(to='nota.TipoEvaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('curso', models.ManyToManyField(to='curso.Curso')),
                ('tipo_evaluacion', models.ManyToManyField(to='nota.TipoEvaluacion')),
            ],
        ),
    ]
