# Generated by Django 2.2.5 on 2019-09-12 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=30, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('realizado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('pago', models.ManyToManyField(to='pago.Pago')),
            ],
        ),
    ]
